FROM maven:3.6.3-openjdk-17 as builder
FROM openjdk:17-jdk-alpine
WORKDIR /project
COPY ../eCARMARKET/pom.xml /project/
COPY ../src /project/src
RUN mvn package

FROM openjdk:17
WORKDIR /usr/src/app/
COPY --from=builder /project/target/*.jar /usr/src/app/
EXPOSE 8081
CMD [ "java", "-jar", "eCARMARKET.jar" ]
