FROM maven:3.6.3-openjdk-17 as builder
WORKDIR /project
COPY /pom.xml /project/
COPY /src /project/src
RUN mvn package

FROM openjdk:17
WORKDIR /usr/src/app/
COPY --from=builder /project/target/*.jar /usr/src/app/
EXPOSE 8081
RUN chmod +x /usr/src/app/eCARMARKET-0.0.1-SNAPSHOT.jar
CMD [ "java", "-jar", "/usr/src/app/eCARMARKET-0.0.1-SNAPSHOT.jar"]
